import type { Localized } from './challenges';

export type LearningContext = { why: Localized; roles: Localized };

export const learningContext: Record<string, LearningContext> = {
  'dft-scan-capture': { why: { zh: 'Scan 提升內部狀態的可控制性與可觀測性，才能載入測試條件並讀回擷取結果。Functional simulation 通過，不代表製造缺陷已被測到；fault coverage 仍需故障模型與 ATPG。', en: 'Scan provides controllability and observability of internal state. Passing functional simulation does not establish manufacturing fault coverage, which needs fault models and ATPG.' }, roles: { zh: 'DFT、RTL Design、SoC Integration、Test Engineering', en: 'DFT, RTL Design, SoC Integration, Test Engineering' } },
  'dft-sram-mbist': { why: { zh: '記憶體可靠度研究需要區分「找出故障」與「修復故障」。MBIST 以控制器自主產生存取並比較預期值；本題故障注入可驗證 checker，而非只在健康模型上得到 pass。', en: 'Memory reliability separates fault detection from repair. MBIST generates accesses and checks expected data; fault injection validates the checker rather than only testing healthy memory.' }, roles: { zh: 'Memory DFT／MBIST、SoC DV、記憶體控制器', en: 'Memory DFT/MBIST, SoC DV, Memory Controllers' } },
  'dft-spare-row-remap': { why: { zh: '備援映射把可修復的壞列替換掉；讀寫必須一致，否則表面能讀到 spare，寫入卻仍落在故障位置。這是記憶體修復概念，並非完整 BIRA/BISR 或 flash 演算法。', en: 'Spare-row remapping must redirect reads and writes consistently. This illustrates memory repair, not a full BIRA/BISR engine or flash algorithm.' }, roles: { zh: 'Memory Design、DFT/BISR、RTL Wrapper、SoC DV', en: 'Memory Design, DFT/BISR, RTL Wrappers, SoC DV' } },
  'lp-glitch-free-clock-gate': { why: { zh: 'Clock gating 減少不必要的時脈切換，但錯誤 gating 可能造成多打一拍或半截 pulse。測試模式也要保有 clock 可控制性；此處刻意使用的 latch 與 mux 漏賦值造成的 latch 不同。', en: 'Clock gating suppresses unnecessary clock activity, but incorrect gating can create extra edges or partial pulses. Test mode needs clock controllability; the intentional gating latch differs from an accidental mux latch.' }, roles: { zh: 'Low Power RTL、DFT、CTS/STA、SoC Integration', en: 'Low-Power RTL, DFT, CTS/STA, SoC Integration' } },
  'lp-operand-isolation': { why: { zh: '控制 output valid 只改變資料是否有意義，不一定減少運算單元內部切換。保持輸入可以減少閒置運算，但是否省電仍要連同新增邏輯與活動率評估，不能拿 cell 數直接當功耗。', en: 'Output-valid controls meaning, not internal activity. Holding inputs suppresses idle computation, but power benefits require activity and overhead analysis; cell count alone is not power.' }, roles: { zh: 'AI Accelerator／HBM-PIM、RTL Design、PPA/Power Analysis', en: 'AI Accelerators/HBM-PIM, RTL Design, PPA/Power Analysis' } },
  'lp-retention-register': { why: { zh: 'Clock gating 仍有供電，power gating 則可能失去狀態。Retention 需要在斷電前保存、穩定供電後還原，且保存狀態所在的供電域不能一起被關掉。', en: 'Clock gating keeps power supplied; power gating can lose state. Retention saves before power loss and restores after stable power while keeping the saved-state supply alive.' }, roles: { zh: 'Low Power RTL、Power-aware DV、UPF/SoC Integration', en: 'Low-Power RTL, Power-Aware DV, UPF/SoC Integration' } },
  'lp-power-sequencer': { why: { zh: '關閉 CPU／加速器電源是 protocol，不是一個 enable：要排空工作、保存狀態、隔離無效輸出，並在喚醒後正確恢復服務。本題只驗證明定的同步協定，真實電源異常與跨域還需額外驗證。', en: 'Power control is a protocol: drain work, save state, isolate invalid outputs, then restore service on wake-up. This checks a specified synchronous contract, not rail faults or CDC signoff.' }, roles: { zh: 'SoC Power Management、CPU/Accelerator RTL、Low Power DV', en: 'SoC Power Management, CPU/Accelerator RTL, Low-Power DV' } },
  'rtl-edge-pulse': { why: { zh: '控制訊號常以 pulse 啟動一次操作；若 level 維持多拍卻重複觸發，可能造成重複寫入或狀態機跳轉。', en: 'Control events often need a one-cycle pulse; repeated triggering can duplicate writes or FSM transitions.' }, roles: { zh: 'RTL Design、SoC Integration、FPGA', en: 'RTL Design, SoC Integration, FPGA' } },
  'rtl-saturating-counter': { why: { zh: '一般二進位 counter 會回捲；效能計數器、credit 與保護閾值常需要飽和行為，邊界沒處理會產生系統級錯誤。', en: 'Binary counters wrap, while performance counters, credits, and protection thresholds often require saturation.' }, roles: { zh: 'RTL Design、DV、Firmware/Hardware Interface', en: 'RTL Design, DV, Firmware/Hardware Interface' } },
  'rtl-latch-debug': { why: { zh: '組合邏輯未完整賦值會推導 latch，造成非預期狀態、時序路徑變複雜，也可能限制 synthesis／P&R 對邏輯重整與時序最佳化。', en: 'Incomplete combinational assignments infer latches, create unintended state, complicate timing paths, and can restrict synthesis/P&R optimization.' }, roles: { zh: 'RTL Design、Synthesis、Lint、DV', en: 'RTL Design, Synthesis, Lint, DV' } },
  'cdc-2ff-level': { why: { zh: '單位元 level 直接跨時脈可能讓亞穩態傳入下游；2-FF 降低傳播機率，但不能保證短 pulse 或多位元資料一致性。', en: 'A single-bit level can become metastable across clocks; 2-FF reduces propagation risk but does not solve short pulses or coherent buses.' }, roles: { zh: 'RTL Design、CDC Signoff、SoC Integration', en: 'RTL Design, CDC Signoff, SoC Integration' } },
  'cdc-reset-release': { why: { zh: '非同步 reset 在 clock edge 附近解除可能違反 recovery/removal；同步解除可避免同一 domain 的暫存器在不同拍離開 reset。', en: 'Asynchronous reset release near a clock edge can violate recovery/removal; synchronized release aligns a domain.' }, roles: { zh: 'RTL Design、CDC/RDC、Physical Design', en: 'RTL Design, CDC/RDC, Physical Design' } },
  'cdc-toggle-pulse': { why: { zh: '短事件跨到慢時脈時可能完全漏採樣；toggle 將事件轉成持續狀態變化，再於目的端還原為單拍 pulse。', en: 'A short event can be missed by a slower clock; toggle encoding preserves it as a state change.' }, roles: { zh: 'RTL Design、SoC/IP Integration、DV', en: 'RTL Design, SoC/IP Integration, DV' } },
  'cdc-gray-pointer': { why: { zh: 'Async FIFO pointer 多位元同時翻轉會被目的端取到混合值；Gray code 讓相鄰值只變一個 bit，保護 pointer 取樣一致性。', en: 'Binary FIFO pointers can be sampled incoherently; Gray code limits adjacent transitions to one bit.' }, roles: { zh: 'RTL Design、CDC Signoff、Interface IP', en: 'RTL Design, CDC Signoff, Interface IP' } },
  'cdc-handshake-bus': { why: { zh: '多位元 bus 逐 bit 同步無法保證同一筆資料；closed-loop handshake 讓資料在取樣期間保持穩定並提供 back-pressure。', en: 'Per-bit synchronization cannot preserve bus coherence; a closed-loop handshake stabilizes data and provides back-pressure.' }, roles: { zh: 'SoC Integration、RTL Design、Interconnect DV', en: 'SoC Integration, RTL Design, Interconnect DV' } },
  'timing-pipeline-path': { why: { zh: 'Critical path 超過 clock period 會造成 setup violation；加入 pipeline 可縮短每級組合延遲，但必須同時管理 latency、valid 與吞吐量。', en: 'Pipelining shortens combinational delay for setup closure but changes latency and requires control alignment.' }, roles: { zh: 'Microarchitecture、RTL Design、Physical Design', en: 'Microarchitecture, RTL Design, Physical Design' } },
  'timing-balanced-max': { why: { zh: '串接 priority chain 的邏輯深度隨輸入增加；平衡樹降低 logic depth，通常更容易達成高頻率。', en: 'A serial priority chain grows in depth; a balanced tree shortens logic depth and is friendlier to high frequency.' }, roles: { zh: 'RTL Design、Synthesis、PPA Optimization', en: 'RTL Design, Synthesis, PPA Optimization' } },
  'timing-valid-retime': { why: { zh: '只移動 data register、沒有同步移動 valid/tag，會把正確結果配到錯誤 transaction，是 retiming 常見的功能性 bug。', en: 'Moving data registers without valid/tag alignment associates results with the wrong transaction.' }, roles: { zh: 'RTL Design、DV、ECO/Timing Closure', en: 'RTL Design, DV, ECO/Timing Closure' } },
  'timing-hold-lab': { why: { zh: 'Hold violation 是資料太早到，與降低 clock frequency 無關；修復必須增加 min-path delay，同時避免破壞 setup 與功能 latency。', en: 'Hold failure means data arrives too early and is not fixed by lowering frequency; repair min delay without breaking setup or function.' }, roles: { zh: 'Physical Design、STA、Signoff、ECO', en: 'Physical Design, STA, Signoff, ECO' } },
  'soc-apb-register': { why: { zh: '低速控制暫存器常以 APB 連接 CPU 與 peripheral；address decode、唯讀／可寫屬性及握手錯誤都會影響軟硬體整合。', en: 'APB commonly connects CPUs to low-speed control registers; decode and access semantics are core integration concerns.' }, roles: { zh: 'SoC Integration、RTL Design、Firmware', en: 'SoC Integration, RTL Design, Firmware' } },
  'soc-round-robin': { why: { zh: '多個 master 共用 bus 或 memory 時需要 arbitration；公平性與 mutual exclusion 決定是否會 starvation 或資料衝突。', en: 'Shared buses and memories need arbitration; fairness and mutual exclusion prevent starvation and conflicts.' }, roles: { zh: 'Interconnect Design、SoC Architecture、DV/Formal', en: 'Interconnect Design, SoC Architecture, DV/Formal' } },
  'verification-fifo-guard': { why: { zh: 'Checker 能在 regression 中自動抓非法 protocol，不必靠人工逐張看 waveform；這是從「跑模擬」進入「自我檢查驗證」的第一步。', en: 'A checker catches protocol violations automatically in regression instead of relying on manual waveform inspection.' }, roles: { zh: 'Design Verification、RTL Design、Formal', en: 'Design Verification, RTL Design, Formal' } },
  'verification-scoreboard-debug': { why: { zh: 'Pipeline、bubble 或 out-of-order 系統不能拿當拍 input/output 直接比；scoreboard 必須追蹤 transaction 與 latency。', en: 'Pipelines and bubbles require transaction- and latency-aware checking rather than same-cycle comparison.' }, roles: { zh: 'CPU/GPU DV、SoC DV、Post-silicon Debug', en: 'CPU/GPU DV, SoC DV, Post-silicon Debug' } },
  'ppa-width-discipline': { why: { zh: '多餘位寬會擴大 adder、register、mux 與 routing load；先以 range analysis 決定位寬，是最直接且可攜的面積／功耗優化。', en: 'Excess width enlarges adders, registers, muxes, and routing load; range analysis is a portable PPA optimization.' }, roles: { zh: 'RTL Design、Low Power、Synthesis/PPA', en: 'RTL Design, Low Power, Synthesis/PPA' } },
  'ppa-shared-adder': { why: { zh: '資源共用以較長 latency 換取較少運算單元；是否值得取決於吞吐量、clock、控制成本與功耗，而不是只看 cell 數。', en: 'Resource sharing trades latency for fewer operators; value depends on throughput, clock, control overhead, and power.' }, roles: { zh: 'Accelerator Architecture、RTL Design、PPA', en: 'Accelerator Architecture, RTL Design, PPA' } },
  'soc-axi-lite-accelerator': { why: { zh: 'CPU 通常不直接驅動加速器內部訊號，而是透過 memory-mapped registers 設定參數、啟動並讀回狀態；AXI-Lite 是常見控制路徑。', en: 'CPUs usually control accelerators through memory-mapped registers; AXI-Lite is a common control path.' }, roles: { zh: 'SoC Integration、Accelerator RTL、ARM Subsystem', en: 'SoC Integration, Accelerator RTL, ARM Subsystem' } },
  'soc-axi-burst-reader': { why: { zh: '大量 tensor／packet 資料不適合用 AXI-Lite 搬移；AXI4 burst master 或 DMA 才能提供吞吐量，並須正確處理 back-pressure 與 RLAST。', en: 'Bulk tensor or packet data needs AXI4 bursts or DMA rather than AXI-Lite, with correct back-pressure and RLAST handling.' }, roles: { zh: 'AI Accelerator、DMA/Interconnect、SoC Integration', en: 'AI Accelerator, DMA/Interconnect, SoC Integration' } },
  'cdc-async-fifo': { why: { zh: 'Async FIFO 是高頻寬 SoC 最常見的多位元 CDC 結構之一；難點不是記憶體本身，而是 pointer coherence、full/empty 與 reset convergence。', en: 'An asynchronous FIFO is a core multi-bit CDC structure; the hard parts are pointer coherence, full/empty logic, and reset convergence.' }, roles: { zh: 'RTL Design、CDC Signoff、Interconnect/Interface IP', en: 'RTL Design, CDC Signoff, Interconnect/Interface IP' } },
  'soc-sram-ip-wrapper': { why: { zh: '真實 SoC 通常透過 memory compiler macro 實作 SRAM；設計者必須理解 active-low pins、read latency、byte write、macro timing arc 與 black-box flow。', en: 'Real SoCs use memory-compiler macros; designers must understand active-low pins, read latency, byte writes, timing arcs, and black-box flows.' }, roles: { zh: 'SoC Integration、Memory Subsystem、RTL/Physical Design', en: 'SoC Integration, Memory Subsystem, RTL/Physical Design' } },
  'verification-formal-miter': { why: { zh: 'Formal equivalence 不靠有限 test vectors；它尋找是否存在讓 golden 與 revised design 不同的輸入，適合 synthesis、ECO 與 RTL refactor 後的等價確認。', en: 'Formal equivalence searches for any input that separates golden and revised designs, making it valuable after synthesis, ECOs, and RTL refactors.' }, roles: { zh: 'Formal Verification、RTL Signoff、ECO/Synthesis', en: 'Formal Verification, RTL Signoff, ECO/Synthesis' } },
  'verification-cnf-sat': { why: { zh: 'SAT 是許多 Formal engine 的核心：RTL 會被 bit-blast 成 Boolean constraints，再轉成 CNF；理解 clause、model 與 counterexample，才能正確解讀 SAT/UNSAT。', en: 'SAT powers many formal engines: RTL is bit-blasted into Boolean constraints and CNF. Clauses, models, and counterexamples explain SAT/UNSAT results.' }, roles: { zh: 'Formal Verification、EDA/CAD、Design Verification', en: 'Formal Verification, EDA/CAD, Design Verification' } },
  'verification-uvm-scoreboard': { why: { zh: 'UVM 的價值不只是 class 語法，而是把 stimulus、monitor、checker 與 coverage 分工；analysis path 接錯會讓 regression 看似在跑卻沒有真正比對。', en: 'UVM separates stimulus, monitoring, checking, and coverage; broken analysis plumbing can make a regression run without actually checking results.' }, roles: { zh: 'CPU/GPU DV、SoC DV、Verification Infrastructure', en: 'CPU/GPU DV, SoC DV, Verification Infrastructure' } },
  'verification-bit-true-requant': { why: { zh: 'AI/DSP accelerator 必須和 software golden model 在每個 bit、rounding 與 saturation 行為一致；只比較浮點誤差可能漏掉硬體 corner-case bug。', en: 'AI/DSP accelerators must match the software golden model bit for bit, including rounding and saturation; floating-point trend checks can miss corner cases.' }, roles: { zh: 'AI Accelerator DV、DSP/Communication IC、Modeling', en: 'AI Accelerator DV, DSP/Communication IC, Modeling' } },
};

export const timingCommandGuide = [
  {
    tool: 'OpenROAD',
    inspect: 'report_checks -path_delay min\nreport_worst_slack -min',
    repair: 'repair_timing -setup\nrepair_timing -hold\nreport_checks -path_delay min',
    note: { zh: '官方流程要求 CTS 與 propagated clocks 後先修 setup，再修 hold。', en: 'The documented flow repairs setup before hold after CTS with propagated clocks.' },
  },
  {
    tool: 'Cadence Innovus',
    inspect: 'timeDesign -postCTS -hold\ntimeDesign -postRoute -hold\nreport_timing',
    repair: 'optDesign -postCTS -hold\noptDesign -postRoute -setup -hold',
    note: { zh: '依 pre/post-CTS、post-route 與 MMMC 設定選擇階段；新版流程與舊版 Encounter 語法可能不同。', en: 'Choose the stage according to pre/post-CTS, post-route, and MMMC setup; legacy Encounter syntax may differ.' },
  },
  {
    tool: 'Synopsys ICC2',
    inspect: 'report_timing -delay_type min\nreport_timing -delay_type max\nreport_qor',
    repair: 'clock_opt\nroute_opt',
    note: { zh: 'ICC2 通常由 clock_opt／route_opt 在目前 scenario 修復；實際 options、app options 與 flow wrapper 必須查該版本 RM／公司腳本。', en: 'ICC2 commonly fixes timing through clock_opt/route_opt in active scenarios; exact options and wrappers must follow the installed release and company flow.' },
  },
];
